version: '3.8'

services:
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
  redis:
    image: redis
    ports:
     - "6379:6379"
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"